import PptxGenJS from 'pptxgenjs'
import type { ImagePresentation } from '@/types'

/**
 * 将图片演示文稿渲染为 PPTX
 * 每张图片作为全屏背景填充幻灯片
 */
export async function renderImagePresentation(
  presentation: ImagePresentation,
  topic: string
): Promise<string> {
  const pptx = new PptxGenJS()

  // 设置演示文稿属性
  pptx.layout = 'LAYOUT_16x9'
  pptx.author = 'AI PPT Creator'
  pptx.title = topic
  pptx.subject = 'Generated by AI Image Mode'

  console.log(`[Image Renderer] Rendering ${presentation.slides.length} slides`)

  for (const slide of presentation.slides) {
    const pptSlide = pptx.addSlide()

    if (slide.imageBase64) {
      // 图片作为全屏背景
      pptSlide.addImage({
        data: `data:image/${slide.imageFormat || 'png'};base64,${slide.imageBase64}`,
        x: 0,
        y: 0,
        w: '100%',
        h: '100%',
      })

      console.log(`[Image Renderer] Added slide ${slide.index + 1}: ${slide.type}`)
    } else {
      // 生成失败的占位页
      pptSlide.background = { color: 'F5F5F5' }

      pptSlide.addText('Image Generation Failed', {
        x: 0.5,
        y: 2,
        w: 9,
        h: 1,
        fontSize: 24,
        color: 'CC0000',
        align: 'center',
        fontFace: 'Microsoft YaHei',
      })

      if (slide.error) {
        pptSlide.addText(slide.error, {
          x: 0.5,
          y: 3,
          w: 9,
          h: 0.5,
          fontSize: 12,
          color: '666666',
          align: 'center',
          fontFace: 'Microsoft YaHei',
        })
      }

      // 显示提示词（调试用）
      if (slide.prompt) {
        pptSlide.addText(`Prompt: ${slide.prompt.slice(0, 200)}...`, {
          x: 0.5,
          y: 4,
          w: 9,
          h: 1,
          fontSize: 10,
          color: '999999',
          align: 'center',
          fontFace: 'Microsoft YaHei',
        })
      }

      console.log(`[Image Renderer] Added error placeholder for slide ${slide.index + 1}`)
    }
  }

  // 导出为 base64
  const base64 = (await pptx.write({ outputType: 'base64' })) as string

  console.log(`[Image Renderer] PPTX generated, size: ${Math.round(base64.length / 1024)} KB`)

  return `data:application/vnd.openxmlformats-officedocument.presentationml.presentation;base64,${base64}`
}
